### ISSUE TITLE
Update Profile Section

### ISSUE THREAD

**Issue by Aakash-bhandari** [Gladiatormain/Task-Manager#1]
I would like to contribute to this project by working on the Profile Section. I will start implementing improvements and will provide updates as I make progress.

**Comment by Gladiatormain** [comment]
Hi Aakash,

Thank you for your interest in contributing to our project and for taking the initiative to work on the Profile section. We're excited to have you on board!

Your willingness to improve the Profile section is much appreciated. Please feel free to go ahead and start working on it. If you have any questions or need any assistance along the way, don't hesitate to ask. We're here to support your contribution.
